// <auto-generated />
using System;
using HealthcareSystemDesign.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthcareSystemDesign.Migrations
{
    [DbContext(typeof(healthcareContext))]
    partial class healthcareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthcareSystemDesign.Models.Appointment", b =>
                {
                    b.Property<int>("ApptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("appt_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppointmentReason")
                        .HasColumnName("appointment_reason")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<DateTime>("ApptDate")
                        .HasColumnName("appt_date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnName("doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnName("patient_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("PatientId")
                        .HasColumnName("patient_id")
                        .HasColumnType("int");

                    b.Property<bool>("VisitRecord")
                        .HasColumnName("visit_record")
                        .HasColumnType("bit");

                    b.HasKey("ApptId")
                        .HasName("PK__Appointm__E43EE996B49BCAA1");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("billing_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BillingAmount")
                        .HasColumnName("billing_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnName("billing_date")
                        .HasColumnType("date");

                    b.Property<bool>("Paid")
                        .HasColumnName("paid")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnName("patient_id")
                        .HasColumnType("int");

                    b.HasKey("BillingId");

                    b.HasIndex("PatientId");

                    b.ToTable("Billing");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.BillingType", b =>
                {
                    b.Property<int>("BillingtypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("billingtype_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillingId")
                        .HasColumnName("billing_id")
                        .HasColumnType("int");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnName("billing_name")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("BillingtypeId");

                    b.HasIndex("BillingId");

                    b.ToTable("Billing_type");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CardPayment", b =>
                {
                    b.Property<string>("ReferenceNo")
                        .HasColumnName("reference_no")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("BillingId")
                        .HasColumnName("billing_id")
                        .HasColumnType("int");

                    b.Property<double>("PaymentAmount")
                        .HasColumnName("payment_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnName("payment_date")
                        .HasColumnType("date");

                    b.HasKey("ReferenceNo")
                        .HasName("PK__Card_Pay__8E8613978E4C79B7");

                    b.HasIndex("BillingId");

                    b.ToTable("Card_Payment");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CashPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("payment_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillingId")
                        .HasColumnName("billing_id")
                        .HasColumnType("int");

                    b.Property<double>("PaymentAmount")
                        .HasColumnName("payment_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnName("payment_date")
                        .HasColumnType("date");

                    b.HasKey("PaymentId")
                        .HasName("PK__Cash_Pay__ED1FC9EABA761058");

                    b.HasIndex("BillingId");

                    b.ToTable("Cash_Payment");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CheckPayment", b =>
                {
                    b.Property<int>("CheckNo")
                        .HasColumnName("check_no")
                        .HasColumnType("int");

                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("billing_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("PaymentAmount")
                        .HasColumnName("payment_amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnName("payment_date")
                        .HasColumnType("date");

                    b.HasKey("CheckNo")
                        .HasName("PK__Check_Pa__C0EA50AF0CBB878C");

                    b.HasIndex("BillingId");

                    b.ToTable("Check_Payment");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.DailyReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("report_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DailyIncome")
                        .HasColumnName("daily_income")
                        .HasColumnType("float");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnName("doctor_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("NoPatients")
                        .HasColumnName("no_patients")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnName("report_date")
                        .HasColumnType("date");

                    b.HasKey("ReportId")
                        .HasName("PK__daily_re__779B7C5892511693");

                    b.ToTable("daily_report");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("doctor_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasColumnName("doctor_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnName("doctor_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<double>("Salary")
                        .HasColumnName("salary")
                        .HasColumnType("float");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.DoctorUnavailability", b =>
                {
                    b.Property<DateTime>("Unavailability")
                        .HasColumnName("unavailability")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnName("doctor_id")
                        .HasColumnType("int");

                    b.HasKey("Unavailability")
                        .HasName("PK__Doctor_u__1F48084FE3C91B96");

                    b.HasIndex("DoctorId");

                    b.ToTable("Doctor_unavailability");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.MedicalReport", b =>
                {
                    b.Property<string>("MedicalreportName")
                        .HasColumnName("medicalreport_name")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("MedicalreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("medicalreport_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PatientId")
                        .HasColumnName("patient_id")
                        .HasColumnType("int");

                    b.Property<byte[]>("ReportFile")
                        .IsRequired()
                        .HasColumnName("report_file")
                        .HasColumnType("varbinary(1)")
                        .HasMaxLength(1);

                    b.HasKey("MedicalreportName")
                        .HasName("PK__Medical___4756A6E8DD1A89CE");

                    b.HasIndex("MedicalreportId");

                    b.HasIndex("PatientId");

                    b.ToTable("Medical_Report");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.MedicalreportType", b =>
                {
                    b.Property<int>("MedicalreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("medicalreport_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnName("report_type")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("MedicalreportId")
                        .HasName("PK__medicalr__9B8597D519BC88A0");

                    b.ToTable("medicalreport_type");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.MonthlyReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("report_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnName("doctor_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<double>("MonthlyIncome")
                        .HasColumnName("monthly_income")
                        .HasColumnType("float");

                    b.Property<int>("NoPatients")
                        .HasColumnName("no_patients")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportMonth")
                        .HasColumnName("report_month")
                        .HasColumnType("date");

                    b.HasKey("ReportId")
                        .HasName("PK__monthly___779B7C58C4F06107");

                    b.ToTable("monthly_report");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Nurse", b =>
                {
                    b.Property<int>("NurseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("nurse_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DoctorId")
                        .HasColumnName("doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("NurseEmail")
                        .IsRequired()
                        .HasColumnName("nurse_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("NurseName")
                        .IsRequired()
                        .HasColumnName("nurse_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<double>("Salary")
                        .HasColumnName("salary")
                        .HasColumnType("float");

                    b.HasKey("NurseId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Nurse");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("patient_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnName("address")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Allergy")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Bloodpressure")
                        .HasColumnName("bloodpressure")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Height")
                        .HasColumnName("height")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasColumnName("insurance")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("PatientEmail")
                        .HasColumnName("patient_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnName("patient_name")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int?>("Pulse")
                        .HasColumnName("pulse")
                        .HasColumnType("int");

                    b.Property<string>("Ssn")
                        .HasColumnName("ssn")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11)
                        .IsUnicode(false);

                    b.Property<int?>("Weight")
                        .HasColumnName("weight")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.VisitRecord", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnName("patient_id")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnName("doctor_id")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnName("prescription")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<DateTime>("VisitDate")
                        .HasColumnName("visit_date")
                        .HasColumnType("date");

                    b.Property<string>("VisitReason")
                        .IsRequired()
                        .HasColumnName("visit_reason")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.Property<bool>("Visited")
                        .HasColumnName("visited")
                        .HasColumnType("bit");

                    b.HasKey("PatientId")
                        .HasName("PK__Visit_Re__4D5CE4760AF2029A");

                    b.HasIndex("DoctorId");

                    b.ToTable("Visit_Record");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Appointment", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Doctor", "Doctor")
                        .WithMany("Appointment")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Appointme__docto__30F848ED")
                        .IsRequired();

                    b.HasOne("HealthcareSystemDesign.Models.Patient", "Patient")
                        .WithMany("Appointment")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Appointme__patie__300424B4");
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Billing", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Patient", "Patient")
                        .WithMany("Billing")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Billing__patient__2D27B809")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.BillingType", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Billing", "Billing")
                        .WithMany("BillingType")
                        .HasForeignKey("BillingId")
                        .HasConstraintName("FK__Billing_t__billi__33D4B598")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CardPayment", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Billing", "Billing")
                        .WithMany("CardPayment")
                        .HasForeignKey("BillingId")
                        .HasConstraintName("FK__Card_Paym__billi__46E78A0C")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CashPayment", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Billing", "Billing")
                        .WithMany("CashPayment")
                        .HasForeignKey("BillingId")
                        .HasConstraintName("FK__Cash_Paym__billi__440B1D61")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.CheckPayment", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Billing", "Billing")
                        .WithMany("CheckPayment")
                        .HasForeignKey("BillingId")
                        .HasConstraintName("FK__Check_Pay__billi__412EB0B6")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.DoctorUnavailability", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Doctor", "Doctor")
                        .WithMany("DoctorUnavailability")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Doctor_un__docto__3E52440B")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.MedicalReport", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.MedicalreportType", "Medicalreport")
                        .WithMany("MedicalReport")
                        .HasForeignKey("MedicalreportId")
                        .HasConstraintName("FK__Medical_R__medic__49C3F6B7")
                        .IsRequired();

                    b.HasOne("HealthcareSystemDesign.Models.Patient", "Patient")
                        .WithMany("MedicalReport")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("FK__Medical_R__patie__4AB81AF0")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.Nurse", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Doctor", "Doctor")
                        .WithMany("Nurse")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Nurse__doctor_id__267ABA7A")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystemDesign.Models.VisitRecord", b =>
                {
                    b.HasOne("HealthcareSystemDesign.Models.Doctor", "Doctor")
                        .WithMany("VisitRecord")
                        .HasForeignKey("DoctorId")
                        .HasConstraintName("FK__Visit_Rec__docto__3B75D760")
                        .IsRequired();

                    b.HasOne("HealthcareSystemDesign.Models.Patient", "Patient")
                        .WithOne("VisitRecord")
                        .HasForeignKey("HealthcareSystemDesign.Models.VisitRecord", "PatientId")
                        .HasConstraintName("FK__Visit_Rec__patie__3A81B327")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
